// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Transactional domain-event outbox. Insert in the same transaction as domain changes.
type OutboxEvent struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
	ProcessedAt   pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Attempts      int32              `db:"attempts" json:"attempts"`
	LastError     pgtype.Text        `db:"last_error" json:"last_error"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
