// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :one
INSERT INTO outbox_events (
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    available_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, occurred_at, available_at, processed_at, attempts, last_error, created_at, updated_at
`

type EnqueueOutboxEventParams struct {
	EventType     string             `db:"event_type" json:"event_type"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, enqueueOutboxEvent,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.AvailableAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.OccurredAt,
		&i.AvailableAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxEvent = `-- name: GetOutboxEvent :one
SELECT id, event_type, aggregate_type, aggregate_id, payload, occurred_at, available_at, processed_at, attempts, last_error, created_at, updated_at
FROM outbox_events
WHERE id = $1
`

func (q *Queries) GetOutboxEvent(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, getOutboxEvent, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.OccurredAt,
		&i.AvailableAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
